sudo: false

language: java
jdk: oraclejdk8

install:
  - mkdir -p ../utils
  - curl -Ls https://github.com/s4u/travis/archive/master.tar.gz \
    | tar -zx --strip-components 2 -C ../utils travis-master/src

script:
  - ../utils/mvn-push.sh clean deploy
  - ../utils/mvn-pr.sh   clean verify


cache:
  directories:
  - $HOME/.m2/repository

before_cache:
  - rm -rfv $HOME/.m2/repository/org/simplify4u/jfatek/

env:
  global:
  - secure: "DUF5exTutNqnGBYHPUEIqdjZyX1jyIcri3NGK+N07KoEQ5tKpkJNPWfGsyESU9JRNGLgHZmdvvdRVGvd6M982sA0/bSYtEYezFp68cBA1/O/8S3LWW47S/x68ey3AHvS5jvSUyIdyr6TGChvny+tAVRnco/s+rau8YiPl4cG7qM="
  - secure: "MgMfBxTG0j77F7AM3918MgwTiLEJPS6ShJzh7+zZwFxcUKOPQAKday+uAMM9WKE+5bRnRCOLXDyXYYyrKaMaL9rvFdFYGsl1pQqHNJ3ct5MYlCRaLoa5F2jkjhfIfjryp8UYEuGOGDfHcLehi6HswkHEV5968k2TeGtKTHC4RIg="
